export const copy = {
  fr: {
    steps: ["Identité", "Domaine", "Partie adverse", "Situation", "Documents", "Consentement"],
    back: "← Précédent",
    next: "Suivant →",
    submit: "Envoyer la demande",
    submitting: "Envoi en cours…",
    success: "Votre demande a bien été enregistrée.",
    successReference: "Référence de votre dossier :",
    successNote: "Le cabinet reviendra vers vous dans les meilleurs délais. Conservez cette référence.",
    error: "Une erreur est survenue. Merci de réessayer ou de nous contacter directement.",
    step1: {
      title: "Vos coordonnées",
      fullName: "Nom complet",
      email: "E-mail",
      phone: "Téléphone",
    },
    step2: {
      title: "Domaine juridique concerné",
      domainPlaceholder: "Sélectionnez un domaine",
    },
    step3: {
      title: "Partie adverse (le cas échéant)",
      opposingPartyName: "Nom de la partie adverse (facultatif)",
      opposingPartyDetails: "Précisions sur la partie adverse (facultatif)",
    },
    step4: {
      title: "Votre situation",
      urgency: "Degré d'urgence",
      description: "Décrivez votre situation",
      descriptionHint: "Minimum 10 caractères.",
    },
    step5: {
      title: "Documents à joindre (facultatif)",
      hint: "PDF, JPG, PNG, DOC ou DOCX — 10 Mo max par fichier, 5 fichiers max.",
      addFiles: "Ajouter des fichiers",
      remove: "Retirer",
      tooMany: "Vous ne pouvez pas joindre plus de 5 fichiers.",
      typeNotAllowed: "Ce type de fichier n'est pas accepté.",
      tooLarge: "Ce fichier dépasse 10 Mo.",
    },
    step6: {
      title: "Récapitulatif et consentement",
      recap: "Vérifiez les informations ci-dessous avant l'envoi.",
      consent:
        "J'accepte que mes informations et documents soient utilisés par FN & PARTNERS pour traiter ma demande.",
    },
    urgencyLabels: { low: "Faible", normal: "Normale", high: "Élevée", urgent: "Urgente" },
  },
  en: {
    steps: ["Identity", "Domain", "Opposing party", "Situation", "Documents", "Consent"],
    back: "← Back",
    next: "Next →",
    submit: "Send Request",
    submitting: "Sending…",
    success: "Your request has been recorded.",
    successReference: "Your file reference:",
    successNote: "The firm will get back to you as soon as possible. Please keep this reference.",
    error: "Something went wrong. Please try again or contact us directly.",
    step1: {
      title: "Your details",
      fullName: "Full name",
      email: "Email",
      phone: "Phone",
    },
    step2: {
      title: "Legal domain concerned",
      domainPlaceholder: "Select a domain",
    },
    step3: {
      title: "Opposing party (if any)",
      opposingPartyName: "Opposing party name (optional)",
      opposingPartyDetails: "Details about the opposing party (optional)",
    },
    step4: {
      title: "Your situation",
      urgency: "Urgency level",
      description: "Describe your situation",
      descriptionHint: "Minimum 10 characters.",
    },
    step5: {
      title: "Documents to attach (optional)",
      hint: "PDF, JPG, PNG, DOC or DOCX — 10 MB max per file, 5 files max.",
      addFiles: "Add files",
      remove: "Remove",
      tooMany: "You cannot attach more than 5 files.",
      typeNotAllowed: "This file type is not accepted.",
      tooLarge: "This file exceeds 10 MB.",
    },
    step6: {
      title: "Summary and consent",
      recap: "Review the information below before sending.",
      consent: "I agree that my information and documents may be used by FN & PARTNERS to process my request.",
    },
    urgencyLabels: { low: "Low", normal: "Normal", high: "High", urgent: "Urgent" },
  },
} as const;
